bower.json
docs/Data/Argonaut/Decode.md
docs/Data/Argonaut/Encode.md
src/Data/Argonaut/Decode.purs
src/Data/Argonaut/Encode.purs
test/Test/Main.purs

Generic deriving

---

bower.json
package.json
src/Data/Argonaut/Decode.purs
src/Data/Argonaut/Encode.purs

- bumped dependencies
- use Type.Proxy
- use type constructor from SigProd in error messages
- remove some imports to prevent warnings
Closes #6

Update for purescript-generics-0.7

---

src/Data/Argonaut/Decode.purs

Decode null as Nothing in decodeJsonMaybe

---

src/Data/Argonaut/Decode.purs

* Include the type constructor name for all errors when decoding a
SigProd
* Distinguish between the 'tag' property missing, and it being the wrong
type

Improve generic decoding errors

---

src/Data/Argonaut/Decode.purs
src/Data/Argonaut/Encode.purs
test/Test/Main.purs

Currently, the instances for `Either` don't record which constructor was used, which means that you get the wrong result if the two types have compatible encodings (for example, `Either String String`, or `Either Number Int`).

Fix either

---

src/Data/Argonaut/Decode/Combinators.purs
test/Test/Main.purs

I'm not sure if this is something you want to include here, but I found it quite useful in my code.
This adds a (.??) combinator to decode optional fields, like (.:?) in Aeson. I'm not really sure how to add that to the existing test suite. Any help there would be much appreciated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/purescript-contrib/purescript-argonaut-codecs/17)

Add a combinator for decoding maybe fields

---

src/Data/Argonaut/Decode/Class.purs
src/Data/Argonaut/Encode/Class.purs

Fixes #22, in a backwards-compatible way.

Lossless Maybe encoding/decoding

---

src/Data/Argonaut/Decode/Class.purs
src/Data/Argonaut/Encode/Class.purs

The decoder for the fixed version does not behave correctly.

Revert `Maybe` codec change

---

src/Data/Argonaut/Decode.purs
src/Data/Argonaut/Decode/Combinators.purs

This PR adds an operator for supplying a default value to `getDefaultField` (`.??`).
This is similar to Aeson's [`.!=`](https://www.stackage.org/haddock/lts-8.21/aeson-1.0.2.1/Data-Aeson.html#v:.-33--61-) operator.
The fixity needs to be less than the `.??` operator so that they compose cleanly.

Add an operator for supplying a default value to getDefaultField

---

bower.json
src/Data/Argonaut/Encode.purs
src/Data/Argonaut/Encode/Combinators.purs
test/Test/Main.purs

This PR updates  purescript-contrib/purescript-argonaut#11.

Add assocOptional and encodeOptional encode combinators 

---

bower.json
src/Data/Argonaut/Decode/Class.purs
src/Data/Argonaut/Decode/Combinators.purs
test/Test/Main.purs

Extends the error message returned in the `Left` result of `getField` and `getFieldOptional`. This will take the message coming from `decodeJson` and prepend it with a helpful message that includes the specific key that failed to decode (e.g. `Value is not a String` will become `Failed to decode 'foo': Value is not a String`).
All tests are still passing, and this doesn't change the API in any way. To manually test you could create a `Json` value with a type that doesn't match what it should and see the new error on decode.
This is a very simple change that will go a long way toward making the decoding error messages more useful, however a more robust solution akin to [Aeson Better Errors](https://harry.garrood.me/blog/aeson-better-errors/) would be ideal. For now though, I think this …

include key in error message from getField functions

---

bower.json
src/Data/Argonaut/Decode/Class.purs
src/Data/Argonaut/Encode/Class.purs
test/Test/Main.purs

Addresses https://github.com/purescript-contrib/purescript-argonaut-codecs/issues/37 by allowing users to call `encodeJson` and `decodeJson` for record types. The relevant classes are implemented using `RowToList`.
We've been using this branch in production at Habito for a little while and we're happy it works! I've also added some basic quickcheck tests to test the encode/decode roundtrip but I can expand on these if you'd like.
I changed `Decode.Class` to export everything, same as `Encode.Class`. If you prefer I can change `Encode.Class` to be more restrictive instead.

Add EncodeJson/DecodeJson instances for records

---

README.md

@natefaubion provided me with a nice neat example of using codecs that made it easy for me to get my head around the module.  I think the example might help to orient new users of the module so I've added it to the README.

Provided a simple example in the documentation to orient new users.

---

README.md
package-lock.json
src/Data/Argonaut/Decode.purs
src/Data/Argonaut/Decode/Combinators.purs
test/Test/Main.purs

Renames decode combinators and introduces a new one that treats `null` values as missing values. See discussion here: #32
The reason for this boils down to the current combinators not behaving as most users would expect, but updating their behavior would break existing codebases without them knowing. So the solution was to rename the functions altogether, now matching their analogues in Haskell's Aeson library.
Also added some tests. I couldn't figure out how to test the decode combinators with QuickCheck. Even for the existing tests, the one that claimed to be testing `.?` (now `.:`) wasn't. So instead I added a suite of manual tests.
`src/Data/Argonaut/Decode/Combinators.purs` contains the meat of the updates. Then the tests also illustrate the intended behavior. 
Beyond running the …

Add expected behavior for null values to decode functions

---

src/Data/Argonaut/Decode/Class.purs
src/Data/Argonaut/Encode/Class.purs

Adds `EncodeJson` and `DecodeJson` instances for Data.Set.Set. Since we already have the `ordered-collections` dependency, this seems like an easy win.
Let me know what you think. Thank you!
-be

Add instances for Data.Set

---

src/Data/Argonaut/Decode/Combinators.purs

I was trying to write some JSON decoders and came accross this typo that confused me momentarily. The description for `getFieldOptional` suggests using itself for slightly different behaviour, when I believe that it should be referring to `getFieldOptional'`

correct a typo in getFieldOptional docs

---

src/Data/Argonaut/Decode/Combinators.purs

This changes `getFieldOptional'` to use `elaborateFailure`, just like its sister function `getFieldOptional`.
```
import Data.Argonaut.Decode (decodeJson)
import Data.Argonaut.Decode.Combinators (getFieldOptional')
import Data.Argonaut.Parser (jsonParser)
import Data.Maybe
import Data.Either
import Prelude
jsonParser "{\"age\": \"26\"}" >>= decodeJson >>= (\obj -> (obj `getFieldOptional'` "age") :: Either String (Maybe Int))
```
Without the change, the result is `(Left "Value is not a Number")`.
With the change, the result is `(Left "Failed to decode key 'age': Value is not a Number")`

Use `elaborateFailure` in `getFieldOptional'`

---

src/Data/Argonaut/Encode/Combinators.purs

A simple fix of a typo in the comments. Should have no impact whatsoever on functionality.

Fix typo in comment at top of Encode.purs

---

src/Data/Argonaut/Encode/Class.purs

This does not parse in `purs` master.

Fix associativity of inline type annotation

---

bower.json
src/Data/Argonaut/Decode/Class.purs
src/Data/Argonaut/Encode/Class.purs

Adds trivial encode/decode instances for `Identity a`. I ran into this when trying to encode a data type that looks like this -
```purescript
data Entity f = Entity
{ guid :: f Guid
, <some other fields here>
}
```
When the entity has a Guid it can be persisted as `Entity Identity`. This is a very common pattern.
However in the absence of an encode instance for `Identity a`, I have to manually encode `Entity` while unwrapping the guid field, which is a bit ugly.

Add encode/decode instances for `Identity a`

---

README.md

Closes #48 and adds an in-depth tutorial to introduce new users to the library, provide them with the tools they need to perform common tasks, and includes a few problem situations along with their solutions at the end. I think it's critical that a new Argonaut user feels comfortable creating encoders and decoders for simple data types without having to look at tests, search for random examples across the web, or rely on Haskell or Scala documentation instead.
All changes are to the README.
There is no new code to test, but if you'd like to try things out in the REPL and make sure there aren't errors, that would help; this also deserves an error-checking proofread.
To read the pretty, non-diff version of the file, use this link:
https://github.com/purescript-contrib/purescript-argonaut-cod …

New tutorial for argonaut-codecs

---

README.md

Corrects the Newtype deriving example with missing `derive` keyword

Correct Newtype instance deriving example

---

src/Data/Argonaut/Decode/Class.purs
src/Data/Argonaut/Decode/Combinators.purs

adds elaborate error in records derived by GDecodeJson too

refactor: elaborate error in records derived by GDecodeJson too, compute rest only on success

---

src/Data/Argonaut/Decode/Class.purs

This is just different syntax that's functionally equivalent. It is covered by, and passes, existing quickCheck tests.
Motivation for this change is that I'm planning on pointing readers of [Ch10](https://book.purescript.org/chapter10.html) (rewrite targeting argonaut in-progress) to `decodeJsonTuple` for guidance on writing their own `DecodeJson` instances in one of the exercises, and I'd like this library example to be as easy as possible for beginners to grok.
This is an extension of #75.

 Beginner-friendly syntax in decodeJsonTuple

---

bower.json
src/Data/Argonaut/Decode/Class.purs
src/Data/Argonaut/Decode/Combinators.purs
src/Data/Argonaut/Decode/Decoders.purs
src/Data/Argonaut/Decode/Errors.purs
test/Test/Main.purs

includes https://github.com/purescript-contrib/purescript-argonaut-codecs/pull/72
implements typed error messages just like in https://github.com/garyb/purescript-codec-argonaut/blob/93265396a942ee322047bb31400e1ca9c16e0e3a/src/Data/Codec/Argonaut.purs#L60-L66
breaking change

Implement typed errors for Json

---

README.md

Fixes broken example so it compiles.
Also adds some simplifications without detracting from what this section teaches.
There are lots of other required fixes in these docs to change `JsonDecodeError` to `String`, but that should probably be another PR.
A bonus goal is to ensure inline snippets always compile by linking them to source files that are compiled as part of CI.

Miror clarifications to multi-arg example

---

docs/CHANGELOG.md
docs/README.md

**Description of the change**
Fixes a small error with the docs showing String instead of JsonDecodeError
Closes #87 
---
**Checklist:**

Fix for #87

---

.github/workflows/ci.yml
packages.dhall
src/Data/Argonaut/Decode/Class.purs
src/Data/Argonaut/Encode/Class.purs

Backlinking to purescript-contrib/governance#35

Update to v0.14.0-rc3

---

CHANGELOG.md
src/Data/Argonaut/Encode/Class.purs
src/Data/Argonaut/Encode/Encoders.purs
test/Test/Main.purs

Added an `EncodeJson` instance for `NonEmptyString`s and a test for the `EncodeJson` and `DecodeJson` instances for `NonEmptyString`s.
---
**Checklist:**

Add encoder for NonEmptyString

---

CHANGELOG.md
src/Data/Argonaut/Decode/Class.purs
test/Test/Main.purs

Decodes missing fields in a record as `Nothing`.
Adds a helper type class `DecodeJsonField`
Fixes #92

Add support for decoding missing record fields to Nothing

---

bower.json
spago.dhall
test/Test/Main.purs

**Description of the change**
Fixes some code warnings and missing direct dependencies that cause the CI to fail.  See ([purescript-contrib/governance#43](https://github.com/purescript-contrib/governance/issues/43)).
---
**Checklist:**

fix warnings and missing direct dependencies causing CI failures

---

.github/workflows/ci.yml
.gitignore
.tidyrc.json
CHANGELOG.md
src/Data/Argonaut/Decode/Class.purs
src/Data/Argonaut/Decode/Decoders.purs
src/Data/Argonaut/Encode/Class.purs
src/Data/Argonaut/Encode/Encoders.purs
test/Test/Main.purs

**Description of the change**
Introduces the [`purs-tidy`](https://github.com/natefaubion/purescript-tidy) formatter. This formatter is a lightly opinionated tool we use to maintain a consistent style in the contrib libraries.
We ordinarily restrict to tools provided by the `core` or `contrib` projects. This tool is not, but it was developed and is maintained by core team members, and because it's a formatter it can't block maintenance or release of this library even in the event something goes catastrophically wrong with it.
---
**Checklist:**

Introduce purs-tidy formatter
